[package]
name = "addon_proxy"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.4"
tokio = { version = "0.2.14", features = [ "macros", "sync", "fs" ] }
futures-util = "0.3.4"
toml = "0.5.6"
http = "0.2.1"
http-serde = "1.0.1"
serde = "1.0.105"
serde_derive = "1.0.105"
serde_bytes = "0.11.3"
sled = "0.31.0"
bincode = "1.2.1"
