[config]
skip_core_tasks = true

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy", "test"]

[tasks.fmt]
description = "Format with rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--",
    "--deny", "warnings",
    "--deny", "clippy::pedantic",
    "--deny", "clippy::nursery",
    "--allow", "clippy::used_underscore_binding", # some libraries break this rule
]

[tasks.test]
description = "Run cargo test"
command = "cargo"
args = ["test"]
