refresh_config_url_path = "/refresh-config"
cache_file_path = "proxy_cache"

# the first match

[[routes]]
from = "sub.domain.com/my-addon"
to = "http://localhost:9999"
# sub.domain.com/my-addon/manifest.json => http://localhost:9999/manifest.json

[[routes]]
from = "my-domain.com"
to = "http://localhost:8080"

[[routes]]
from = "sub.domain.com"
to = "http://localhost:8080"

[[routes]]
from = "dont-validate.com"
to = "http://localhost:8080"
validate = false   # Note: allow /manifest.json ; bad_request on fail

[[routes]]
from = "*"
to = "http://localhost:8000"
validate = false

